# Generated by Django 2.2.2 on 2019-06-07 13:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0004_auto_20190607_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
